management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, info, health